/* tslint:disable */
/* eslint-disable */
/**
 * Yan Yun — магазин китайского чая
 * Документация REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
	/**
	 * E-mail
	 * @type {string}
	 * @memberof CreateUserDto
	 */
	email: string;
	/**
	 * Пароль
	 * @type {string}
	 * @memberof CreateUserDto
	 */
	password: string;
	/**
	 * Роль
	 * @type {string}
	 * @memberof CreateUserDto
	 */
	role?: CreateUserDtoRoleEnum;
}

export function CreateUserDtoFromJSON(json: any): CreateUserDto {
	return CreateUserDtoFromJSONTyped(json, false);
}

export function CreateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDto {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		email: json["email"],
		password: json["password"],
		role: !exists(json, "role") ? undefined : json["role"],
	};
}

export function CreateUserDtoToJSON(value?: CreateUserDto | null): any {
	if (value === undefined) {
		return null;
	}
	if (value === null) {
		return null;
	}
	return {
		email: value.email === undefined ? undefined : value.email,
		password: value.password === undefined ? undefined : value.password,
		role: value.role === undefined ? undefined : value.role,
	};
}

/**
 * @export
 * @enum {string}
 */
export enum CreateUserDtoRoleEnum {
	customer = "customer",
	business = "business",
	admin = "admin",
	root = "root",
}
