/* tslint:disable */
/* eslint-disable */
/**
 * Yan Yun — магазин китайского чая
 * Документация REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RegisterDTO
 */
export interface RegisterDTO {
	/**
	 * E-mail
	 * @type {string}
	 * @memberof RegisterDTO
	 */
	email: string;
	/**
	 * Пароль
	 * @type {string}
	 * @memberof RegisterDTO
	 */
	password: string;
}

export function RegisterDTOFromJSON(json: any): RegisterDTO {
	return RegisterDTOFromJSONTyped(json, false);
}

export function RegisterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDTO {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		email: json["email"],
		password: json["password"],
	};
}

export function RegisterDTOToJSON(value?: RegisterDTO | null): any {
	if (value === undefined) {
		return null;
	}
	if (value === null) {
		return null;
	}
	return {
		email: value.email === undefined ? undefined : value.email,
		password: value.password === undefined ? undefined : value.password,
	};
}
