/* tslint:disable */
/* eslint-disable */
/**
 * Yan Yun — магазин китайского чая
 * Документация REST API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import { ImageEntity, ImageEntityFromJSON, ImageEntityFromJSONTyped, ImageEntityToJSON } from "./";

/**
 *
 * @export
 * @interface UserDto
 */
export interface UserDto {
	/**
	 *
	 * @type {string}
	 * @memberof UserDto
	 */
	id?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserDto
	 */
	email: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserDto
	 */
	password: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserDto
	 */
	role: UserDtoRoleEnum;
	/**
	 *
	 * @type {string}
	 * @memberof UserDto
	 */
	firstName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserDto
	 */
	middleName?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserDto
	 */
	lastName?: string;
	/**
	 *
	 * @type {Date}
	 * @memberof UserDto
	 */
	birthDay?: Date;
	/**
	 *
	 * @type {string}
	 * @memberof UserDto
	 */
	phone?: string;
	/**
	 *
	 * @type {string}
	 * @memberof UserDto
	 */
	gender?: UserDtoGenderEnum;
	/**
	 *
	 * @type {string}
	 * @memberof UserDto
	 */
	city?: string;
	/**
	 *
	 * @type {ImageEntity}
	 * @memberof UserDto
	 */
	avatar?: ImageEntity;
	/**
	 *
	 * @type {boolean}
	 * @memberof UserDto
	 */
	hasEmailAgree?: boolean;
	/**
	 *
	 * @type {boolean}
	 * @memberof UserDto
	 */
	hasSMSAgree?: boolean;
	/**
	 *
	 * @type {boolean}
	 * @memberof UserDto
	 */
	hasPushNotificationAgree?: boolean;
}

export function UserDtoFromJSON(json: any): UserDto {
	return UserDtoFromJSONTyped(json, false);
}

export function UserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDto {
	if (json === undefined || json === null) {
		return json;
	}
	return {
		id: !exists(json, "id") ? undefined : json["id"],
		email: json["email"],
		password: json["password"],
		role: json["role"],
		firstName: !exists(json, "firstName") ? undefined : json["firstName"],
		middleName: !exists(json, "middleName") ? undefined : json["middleName"],
		lastName: !exists(json, "lastName") ? undefined : json["lastName"],
		birthDay: !exists(json, "birthDay") ? undefined : new Date(json["birthDay"]),
		phone: !exists(json, "phone") ? undefined : json["phone"],
		gender: !exists(json, "gender") ? undefined : json["gender"],
		city: !exists(json, "city") ? undefined : json["city"],
		avatar: !exists(json, "avatar") ? undefined : ImageEntityFromJSON(json["avatar"]),
		hasEmailAgree: !exists(json, "hasEmailAgree") ? undefined : json["hasEmailAgree"],
		hasSMSAgree: !exists(json, "hasSMSAgree") ? undefined : json["hasSMSAgree"],
		hasPushNotificationAgree: !exists(json, "hasPushNotificationAgree")
			? undefined
			: json["hasPushNotificationAgree"],
	};
}

export function UserDtoToJSON(value?: UserDto | null): any {
	if (value === undefined) {
		return null;
	}
	if (value === null) {
		return null;
	}
	return {
		id: value.id === undefined ? undefined : value.id,
		email: value.email === undefined ? undefined : value.email,
		password: value.password === undefined ? undefined : value.password,
		role: value.role === undefined ? undefined : value.role,
		firstName: value.firstName === undefined ? undefined : value.firstName,
		middleName: value.middleName === undefined ? undefined : value.middleName,
		lastName: value.lastName === undefined ? undefined : value.lastName,
		birthDay: value.birthDay === undefined ? undefined : value.birthDay.toISOString(),
		phone: value.phone === undefined ? undefined : value.phone,
		gender: value.gender === undefined ? undefined : value.gender,
		city: value.city === undefined ? undefined : value.city,
		avatar: ImageEntityToJSON(value.avatar),
		hasEmailAgree: value.hasEmailAgree === undefined ? undefined : value.hasEmailAgree,
		hasSMSAgree: value.hasSMSAgree === undefined ? undefined : value.hasSMSAgree,
		hasPushNotificationAgree:
			value.hasPushNotificationAgree === undefined ? undefined : value.hasPushNotificationAgree,
	};
}

/**
 * @export
 * @enum {string}
 */
export enum UserDtoRoleEnum {
	customer = "customer",
	business = "business",
	admin = "admin",
	root = "root",
}
/**
 * @export
 * @enum {string}
 */
export enum UserDtoGenderEnum {
	male = "male",
	female = "female",
}
